#! /bin/sh

sxhkd -c ~/.config/sxhkd/sxhkdrc &

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
    xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --output eDP --mode 1920x1080 --rotate normal --right-of HDMI-A-0
fi

bspc monitor HDMI-A-0 -d I II III IV V
bspc monitor eDP -d  VI VII VIII IX X 



bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

exec nitrogen --restore & # restore background
exec ~/.config/polybar/launch.sh # run polybar
exec picom & # run compositor

