#! /bin/sh

sxhkd -c ~/.config/sxhkd/sxhkdrc &

bspc monitor eDP -d  I II III IV V VI VII VIII 

~/.local/bin/startup

if [[ $(xrandr -q | grep "$internal_monitor connected") ]]; then
xrandr --output eDP --right-of HDMI-A-0
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


exec picom & # run compositor
