#!/bin/sh

internal_monitor=HDMI-A-0 
external_monitor=eDP
monitor_add() {
	desktops=4 # How many desktops to move to the second monitor

	for desktop in $(bspc query -D -m $external_monitor | sed "$desktops"q)
  do
		bspc desktop $desktop --to-monitor $internal_monitor
  done

  # Remove "Desktop" created by bspwm
  bspc desktop Desktop --remove
}

monitor_remove() {

	bspc monitor $external_monitor -a Desktop # Temp desktop because one desktop required per monitor

	# Move everything to external monitor to reorder desktops
	for desktop in $(bspc query -D -m $external_monitor)
	do
		bspc desktop $desktop --to-monitor $internal_monitor
	done

	# Now move everything back to internal monitor
	bspc monitor $internal_monitor -a Desktop # Temp desktop

	for desktop in $(bspc query -D -m $internal_monitor)
	do
		bspc desktop $desktop --to-monitor $external_monitor
	done

	
	bspc desktop Desktop --remove > ~/Srivania/leggi.txt
}

if [[ $(xrandr -q | grep "$internal_monitor connected") ]]; then
    monitor_add
else
    monitor_remove
fi

nitrogen --restore & # restore background
~/.config/polybar/launch.sh # run polybar
